# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-16.04

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- script: 'npm install'
  displayName: 'Install NPM deps'
- script: 'npm run compile'
  displayName: 'Compile Typescript'
- script: 'node out/test.js'
  displayName: 'Run tests'
  failOnStderr: true