background="default"
text="#f8f8f2"
subtle="#6272a4"
warning-text="#ff5555"
text-special-one="#8be9fd"
text-special-two="#ff79c6"
top-bar-background="default"
top-bar-text="#f8f8f2"
status-bar-background="#282a36"
status-bar-text="#f8f8f2"
status-bar-view-background="#6272a4"
status-bar-view-text="#f8f8f2"
list-selected-background="#ff79c6"
list-selected-text="#282a36"
list-selected-inactive-background="#bd93f9"
list-selected-inactive-text="#282a36"
controls-text="#f8f8f8"
controls-highlight="#8be9fd"
autocomplete-background="#272822"
autocomplete-text="#f8f8f8"
autocomplete-selected-background="#44475a"
autocomplete-selected-text="#f8f8f2"
button-color-one="#ff79c6"
button-color-two="#272822"
timeline-name-background="default"
timeline-name-text="#6272a4"
command-text="#f8f8f2"
