mouse: true
messages_limit: 50
timestamps: false
editor: default
keys:
    cancel: Esc
    guilds_tree:
        focus: Alt+Rune[r]
    messages_text:
        focus: Alt+Rune[s]
        show_image: Rune[m]
        copy_content: Rune[c]
        reply: Rune[R]
        reply_mention: Rune[P]
        select_reply: Rune[s]
        select_previous: Rune[i]
        select_next: Rune[e]
        select_first: Rune[o]
        select_last: Rune[n]
    message_input:
        focus: Alt+Rune[t]
        send: Enter
        paste: Ctrl+V
        launch_editor: Ctrl+E
theme:
    border: true
    border_color: default
    border_padding: [0, 0, 1, 1]
    title_color: default 
    background_color: default
    guilds_tree:
        graphics: true
    messages_text:
        author_color: purple
    message_input: {}
